baseURL = "/"
languageCode = "en-us"
# Title of your site
title = "Gerard Torrats-Espinosa"
# Used as meta data; describe your site to make Google Bots happy 
description = "Department of Sociology and Data Science Institute at Columbia University"
#Put in your tracking code without quotes like this: UA-XXXXXX..
googleAnalytics = ""
# Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
openGraph = true
copyright = "Gerard Torrats-Espinosa. Built with <a href='https://gohugo.io/' target='_blank'>Hugo</a>"


[menu]

  [[menu.main]]
  name = "Home"
  URL = "/"
  identifier = "home"
  weight = 1

[[menu.main]]
  name = "CV"
  url = "/cv"
  identifier = "cv"
  weight = 2
  
[[menu.main]]
  name = "Research"
  url = "/research"
  identifier = "research"
  weight = 3
  
[[menu.main]]
  name = "Data"
  url = "/data"
  identifier = "data"
  weight = 4

[[menu.main]]
  name = "Teaching"
  url = "/teaching"
  identifier = "teaching"
  weight = 5

[[menu.main]]
  name = "Resources"
  url = "/resources"
  identifier = "resources"
  weight = 6

  
[[menu.main]]
  name = "Blog"
  url = "/blog"
  identifier = "blog"
  weight = 7


[params]
logo = ""
mail = "info@companyname.com"
mobile = "1234565523"
# Google Analitycs
googleAnalitycsID = "Your ID"


[params.font]
  name = "Poppins"
  sizes = "600"